name: Run Rest Assured API Tests

on:
    push:
    pull_request:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            # =========================
            # Checkout repository
            # =========================
            - name: Checkout repository
              uses: actions/checkout@v4

            # =========================
            # Set up Java 21
            # =========================
            - name: Set up JDK21
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: "21"
                  cache: 'maven'


            # =========================
            # Run Maven tests
            # =========================
            - name: Run Maven Tests
              run: ./mvnw -B clean test -DCI=true

            # =========================
            # Upload Surefire test reports
            # =========================
            - name: Upload surefire test reports
              uses: actions/upload-artifact@v4
              with:
                  name: surefire-reports
                  path: target/surefire-reports

            # =========================
            # Generate Allure Report
            # =========================
            - name: Generate Allure Report
              run: ./mvnw allure:report

            # =========================
            # Check Allure files
            # =========================
            - name: Check Allure Report
              run: |
                  echo "=== Allure results ==="
                  find target/allure-results -maxdepth 1 -type f | head -20

                  echo "=== Generated Allure report ==="
                  find target/site/allure-maven-plugin -maxdepth 2 -type f | head -50

            # =========================
            # Prepare GitHub Pages folder
            # =========================
            - name: Prepare GitHub Pages folder
              run: |
                  rm -rf public
                  mkdir -p public

                  cp -r target/site/allure-maven-plugin/* public/

                  echo "=== Public folder ==="
                  find public -maxdepth 2 -type f | head -50

            # =========================
            # Deploy to GitHub Pages
            # =========================
            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: public
                  branch: gh-pages
